#! /bin/sh

set -e

srcdir="$(dirname "$0")"
test -z "$srcdir" && srcdir=.

cd "$srcdir"
depsdir="../kernel_deps"
mkdir -p "$depsdir"

clone_repo_commit() {
    if test -d "$2/.git"; then
        git -C "$2" reset --hard
        git -C "$2" clean -fd
        if ! git -C "$2" -c advice.detachedHead=false checkout $3; then
            rm -rf "$2"
        fi
    else
        if test -d "$2"; then
            echo "error: '$2' is not a Git repository" 1>&2
            exit 1
        fi
    fi
    if ! test -d "$2"; then
        git clone $1 "$2"
        if ! git -C "$2" -c advice.detachedHead=false checkout $3; then
            rm -rf "$2"
            exit 1
        fi
    fi
}

rm -f "$depsdir/.deps-obtained"

clone_repo_commit \
    https://github.com/osdev0/freestanding-c-hdrs.git \
    "$depsdir/freestanding-c-hdrs" \
    38fed4e1e3365733ddbfa03b0a28936243ad31e9

clone_repo_commit \
    https://github.com/osdev0/cc-runtime.git \
    "$depsdir/cc-runtime" \
    dae79833b57a01b9fd3e359ee31def69f5ae899b

clone_repo_commit \
    https://github.com/Limine-Bootloader/limine-protocol.git \
    "$depsdir/limine-protocol" \
    da65184e91f80fcb397270121b1e2515a11e01ee

clone_repo_commit \
    https://github.com/mintsuki/flanterm.git \
    "$depsdir/flanterm" \
    3e311fe2ce4f663273c22d1a229745bc53afa930

touch "$depsdir/.deps-obtained"

printf "\nDependencies obtained successfully.\n"
